# Tensors
Tensor와 Numpy array는 Bridge를 통해 편하게 변환하여 사용할 수 있다.

In [2]:
import torch
import numpy as np

## Tensor 초기화하는 예제들

In [4]:
# directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
# from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
# from another tensor
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6775, 0.4384],
        [0.2961, 0.0464]])


In [8]:
# with random or constant values
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.5917, 0.4252, 0.2550],
        [0.3278, 0.2867, 0.2517]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성

In [9]:
tensor = torch.rand(3, 4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


## 텐서의 명령

In [12]:
print(f"Before: {tensor.device}")
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(f"After: {tensor.device}")

Before: cpu
After: cpu


In [13]:
torch.cuda.is_available()
# 내 맥북은 nvidia GPU가 없을 뿐더러, 애초에 nvidia와 apple이랑 결별한지 좀 됨

False